<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>7db11f3f-5651-4849-8ca4-4d9882326a39</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set 'the name' to "Jones" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
